In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
data_training_awal= pd.read_excel('D:\\JAMALI FORECASTING\\B_train_data.xlsx', index_col=0)
data_training= data_training_awal[47:].astype('float32').copy()
data_training

,Beban,Jam_sin,Jam_cos,Hari_sin,Hari_cos,Bulan_sin,Bulan_cos,Holiday_Impact,Suhu_PCA
Date,,,,,,,,,
2022-01-02 00:00:00,17928.000000,0.000000,1.000000,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-3.938439
2022-01-02 00:30:00,17506.000000,0.130526,0.991445,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-4.090625
2022-01-02 01:00:00,17293.000000,0.258819,0.965926,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-4.242810
2022-01-02 01:30:00,17108.000000,0.382683,0.923880,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-4.406652
2022-01-02 02:00:00,16876.000000,0.500000,0.866025,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-4.570495
...,...,...,...,...,...,...,...,...,...
2024-10-30 22:00:00,29019.070312,-0.500000,0.866025,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,0.447690
2024-10-30 22:30:00,28465.740234,-0.382683,0.923880,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,0.134316
2024-10-30 23:00:00,27755.750000,-0.258819,0.965926,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-0.179059
2024-10-30 23:30:00,27277.500000,-0.130526,0.991445,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-0.402285
2024-10-31 00:00:00,26757.400391,0.000000,1.000000,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-0.625510

In [3]:
last_data_training= data_training.tail(1).copy()
data_training= data_training[:-1].copy()
last_data_training

,Beban,Jam_sin,Jam_cos,Hari_sin,Hari_cos,Bulan_sin,Bulan_cos,Holiday_Impact,Suhu_PCA
Date,,,,,,,,,
2024-10-31,26757.400391,0.0,1.0,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-0.62551

In [4]:
data_training

,Beban,Jam_sin,Jam_cos,Hari_sin,Hari_cos,Bulan_sin,Bulan_cos,Holiday_Impact,Suhu_PCA
Date,,,,,,,,,
2022-01-02 00:00:00,17928.000000,0.000000,1.000000,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-3.938439
2022-01-02 00:30:00,17506.000000,0.130526,0.991445,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-4.090625
2022-01-02 01:00:00,17293.000000,0.258819,0.965926,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-4.242810
2022-01-02 01:30:00,17108.000000,0.382683,0.923880,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-4.406652
2022-01-02 02:00:00,16876.000000,0.500000,0.866025,-0.781832,0.623490,0.0,1.000000e+00,1.012018,-4.570495
...,...,...,...,...,...,...,...,...,...
2024-10-30 21:30:00,29717.320312,-0.608761,0.793353,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,0.843025
2024-10-30 22:00:00,29019.070312,-0.500000,0.866025,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,0.447690
2024-10-30 22:30:00,28465.740234,-0.382683,0.923880,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,0.134316
2024-10-30 23:00:00,27755.750000,-0.258819,0.965926,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-0.179059
2024-10-30 23:30:00,27277.500000,-0.130526,0.991445,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-0.402285

In [5]:
df = data_training.copy()

# 1. Hitung sudut kembali menggunakan arctan2(sin, cos)
# Fungsi ini mengembalikan nilai sudut dalam satuan radian
angles = np.arctan2(df['Hari_sin'], df['Hari_cos'])

# 2. Kembalikan ke angka hari dalam rentang 0 hingga 6
# Operasi modulo 7 memastikan angka negatif dari arctan2 kembali ke putaran yang benar
df['Hari_Indeks'] = np.round((angles * 7) / (2 * np.pi)).astype(int) % 7

In [6]:
df['Hari_Indeks'].unique()

array([6, 0, 1, 2, 3, 4, 5])

In [7]:
df_senin= df[df['Hari_Indeks'] ==0]
df_senin = df_senin.drop(columns=['Hari_Indeks']).copy()
df_senin

,Beban,Jam_sin,Jam_cos,Hari_sin,Hari_cos,Bulan_sin,Bulan_cos,Holiday_Impact,Suhu_PCA
Date,,,,,,,,,
2022-01-03 00:00:00,19210.000000,0.000000,1.000000,0.0,1.0,0.0,1.000000e+00,1.012018,-4.183629
2022-01-03 00:30:00,19023.000000,0.130526,0.991445,0.0,1.0,0.0,1.000000e+00,1.012018,-4.457446
2022-01-03 01:00:00,18850.000000,0.258819,0.965926,0.0,1.0,0.0,1.000000e+00,1.012018,-4.731263
2022-01-03 01:30:00,18607.000000,0.382683,0.923880,0.0,1.0,0.0,1.000000e+00,1.012018,-4.907955
2022-01-03 02:00:00,18430.000000,0.500000,0.866025,0.0,1.0,0.0,1.000000e+00,1.012018,-5.084647
...,...,...,...,...,...,...,...,...,...
2024-10-28 21:30:00,29322.710938,-0.608761,0.793353,0.0,1.0,-1.0,-1.836970e-16,1.012018,0.852978
2024-10-28 22:00:00,28681.539062,-0.500000,0.866025,0.0,1.0,-1.0,-1.836970e-16,1.012018,0.531439
2024-10-28 22:30:00,28172.419922,-0.382683,0.923880,0.0,1.0,-1.0,-1.836970e-16,1.012018,0.260008
2024-10-28 23:00:00,27724.839844,-0.258819,0.965926,0.0,1.0,-1.0,-1.836970e-16,1.012018,-0.011424
2024-10-28 23:30:00,27262.011719,-0.130526,0.991445,0.0,1.0,-1.0,-1.836970e-16,1.012018,-0.272631

In [8]:
# Daftar nama hari untuk penamaan file
nama_hari = ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu']

# Loop untuk memproses setiap hari berdasarkan indeks 0 sampai 6
for i, hari in enumerate(nama_hari):
    # 1. Filter data berdasarkan indeks hari (0=Senin, 1=Selasa, dst)
    df_temp = df[df['Hari_Indeks'] == i].copy()
    
    # 2. Hapus kolom 'Hari_Indeks' agar file excel lebih bersih seperti contoh Anda
    df_temp = df_temp.drop(columns=['Hari_Indeks'])
    
    # 3. Simpan ke Excel dengan format nama yang diminta
    nama_file = f'D:\\JAMALI FORECASTING\\PER_HARI\\DATA_HARI\\data_{hari}_train.xlsx'
    df_temp.to_excel(nama_file, index=True)
    
    print(f'Berhasil menyimpan: {nama_file}')

Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_senin_train.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_selasa_train.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_rabu_train.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_kamis_train.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_jumat_train.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_sabtu_train.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_minggu_train.xlsx

# TESTING

In [9]:
last_data_training

,Beban,Jam_sin,Jam_cos,Hari_sin,Hari_cos,Bulan_sin,Bulan_cos,Holiday_Impact,Suhu_PCA
Date,,,,,,,,,
2024-10-31,26757.400391,0.0,1.0,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-0.62551

In [10]:
data_validation_awal= pd.read_excel('D:\\JAMALI FORECASTING\\B_test_data.xlsx', index_col=0)
data_validation= data_validation_awal[:~24].astype('float32').copy()
data_validation

,Beban,Jam_sin,Jam_cos,Hari_sin,Hari_cos,Bulan_sin,Bulan_cos,Holiday_Impact,Suhu_PCA
Date,,,,,,,,,
2024-10-31 00:30:00,26460.919922,0.130526,0.991445,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-0.829108
2024-10-31 01:00:00,26184.929688,0.258819,0.965926,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-1.032705
2024-10-31 01:30:00,25976.689453,0.382683,0.923880,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-1.284443
2024-10-31 02:00:00,25745.220703,0.500000,0.866025,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-1.536183
2024-10-31 02:30:00,25441.970703,0.608761,0.793353,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-1.717856
...,...,...,...,...,...,...,...,...,...
2025-10-29 21:30:00,29000.099609,-0.608761,0.793353,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-1.283128
2025-10-29 22:00:00,28302.843750,-0.500000,0.866025,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-1.492234
2025-10-29 22:30:00,27757.216797,-0.382683,0.923880,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-1.727889
2025-10-29 23:00:00,27084.208984,-0.258819,0.965926,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-1.963544
2025-10-29 23:30:00,26643.658203,-0.130526,0.991445,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-2.159608

In [11]:
data_validation = pd.concat([last_data_training, data_validation])
data_validation

,Beban,Jam_sin,Jam_cos,Hari_sin,Hari_cos,Bulan_sin,Bulan_cos,Holiday_Impact,Suhu_PCA
Date,,,,,,,,,
2024-10-31 00:00:00,26757.400391,0.000000,1.000000,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-0.625510
2024-10-31 00:30:00,26460.919922,0.130526,0.991445,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-0.829108
2024-10-31 01:00:00,26184.929688,0.258819,0.965926,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-1.032705
2024-10-31 01:30:00,25976.689453,0.382683,0.923880,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-1.284443
2024-10-31 02:00:00,25745.220703,0.500000,0.866025,0.433884,-0.900969,-1.0,-1.836970e-16,1.012018,-1.536183
...,...,...,...,...,...,...,...,...,...
2025-10-29 21:30:00,29000.099609,-0.608761,0.793353,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-1.283128
2025-10-29 22:00:00,28302.843750,-0.500000,0.866025,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-1.492234
2025-10-29 22:30:00,27757.216797,-0.382683,0.923880,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-1.727889
2025-10-29 23:00:00,27084.208984,-0.258819,0.965926,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-1.963544
2025-10-29 23:30:00,26643.658203,-0.130526,0.991445,0.974928,-0.222521,-1.0,-1.836970e-16,1.012018,-2.159608

In [12]:
df_testing = data_validation.copy()
# 1. Hitung sudut kembali menggunakan arctan2(sin, cos)
# Fungsi ini mengembalikan nilai sudut dalam satuan radian
angles = np.arctan2(df_testing['Hari_sin'], df_testing['Hari_cos'])

# 2. Kembalikan ke angka hari dalam rentang 0 hingga 6
# Operasi modulo 7 memastikan angka negatif dari arctan2 kembali ke putaran yang benar
df_testing['Hari_Indeks'] = np.round((angles * 7) / (2 * np.pi)).astype(int) % 7

In [13]:
df_testing['Hari_Indeks'].unique()

array([3, 4, 5, 6, 0, 1, 2])

In [14]:
df_testing[df_testing['Hari_Indeks']==0]

,Beban,Jam_sin,Jam_cos,Hari_sin,Hari_cos,Bulan_sin,Bulan_cos,Holiday_Impact,Suhu_PCA,Hari_Indeks
Date,,,,,,,,,,
2024-11-04 00:00:00,22075.419922,0.000000,1.000000,0.0,1.0,-0.866025,5.000000e-01,1.012018,-1.562493,0
2024-11-04 00:30:00,21979.380859,0.130526,0.991445,0.0,1.0,-0.866025,5.000000e-01,1.012018,-1.928949,0
2024-11-04 01:00:00,21805.240234,0.258819,0.965926,0.0,1.0,-0.866025,5.000000e-01,1.012018,-2.295406,0
2024-11-04 01:30:00,21594.500000,0.382683,0.923880,0.0,1.0,-0.866025,5.000000e-01,1.012018,-2.425529,0
2024-11-04 02:00:00,21483.750000,0.500000,0.866025,0.0,1.0,-0.866025,5.000000e-01,1.012018,-2.555654,0
...,...,...,...,...,...,...,...,...,...,...
2025-10-27 21:30:00,29025.169922,-0.608761,0.793353,0.0,1.0,-1.000000,-1.836970e-16,1.012018,-1.214339,0
2025-10-27 22:00:00,28335.880859,-0.500000,0.866025,0.0,1.0,-1.000000,-1.836970e-16,1.012018,-1.438910,0
2025-10-27 22:30:00,27807.810547,-0.382683,0.923880,0.0,1.0,-1.000000,-1.836970e-16,1.012018,-1.631499,0
2025-10-27 23:00:00,27508.160156,-0.258819,0.965926,0.0,1.0,-1.000000,-1.836970e-16,1.012018,-1.824088,0
2025-10-27 23:30:00,26690.779297,-0.130526,0.991445,0.0,1.0,-1.000000,-1.836970e-16,1.012018,-2.001632,0

In [15]:
# Daftar nama hari untuk penamaan file
df= df_testing.copy()
nama_hari = ['senin', 'selasa', 'rabu', 'kamis', 'jumat', 'sabtu', 'minggu']

# Loop untuk memproses setiap hari berdasarkan indeks 0 sampai 6
for i, hari in enumerate(nama_hari):
    # 1. Filter data berdasarkan indeks hari (0=Senin, 1=Selasa, dst)
    df_temp = df[df['Hari_Indeks'] == i].copy()
    
    # 2. Hapus kolom 'Hari_Indeks' agar file excel lebih bersih seperti contoh Anda
    df_temp = df_temp.drop(columns=['Hari_Indeks'])
    
    # 3. Simpan ke Excel dengan format nama yang diminta
    nama_file = f'D:\\JAMALI FORECASTING\\PER_HARI\\DATA_HARI\\data_{hari}_testing.xlsx'
    df_temp.to_excel(nama_file, index=True)
    
    print(f'Berhasil menyimpan: {nama_file}')

Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_senin_testing.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_selasa_testing.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_rabu_testing.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_kamis_testing.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_jumat_testing.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_sabtu_testing.xlsx
Berhasil menyimpan: D:\JAMALI FORECASTING\PER_HARI\DATA_HARI\data_minggu_testing.xlsx